services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: <KSGIegmgQSV3GG6cX2sifJm4qrl0Tb5xO9EvHaSoylttx6wOwEp1tX4a0_8hEsUJT3BlbkFJaX1ssdQp2Ywp8uoLbwK__hw8LIKyww5jN-WIACwzPbqCLviss6yrZYjzIEylTEwA>
      - key: CHANNELS
        value: <your-twitch-channel>
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "7"
      - key: MODEL_NAME
        value: "gpt-4"
      - key: COMMAND_NAME
        value: "tazcidbot"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "Tazcidbot"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: <your-twitch-auth>
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "true"
      - key: ENABLE_CHANNEL_POINTS
        value: "true"
      - key: COOLDOWN_DURATION
        value: "10"
